import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Heade from "@/components/layout/heade";
import Scripts from "@/components/layout/scripts";
import Nav from "@/components/global/nav";
import Indexlayout from "@/components/layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-static";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      className="light lenis lenis-smooth"
      lang="en"
    >
      <Heade />
      <body
        suppressHydrationWarning
        className="bg-background-2 dark dark:bg-background-5"
      >
        <Indexlayout>{children}</Indexlayout>
        <Scripts />
      </body>
    </html>
  );
}
